// SPDX-License-Identifier: CC0-1.0
// Public-domain example code (CC0) - see LICENSE. The CAS BACnet Stack itself is
// a separate, commercially licensed product and is not covered by CC0.
// =============================================================================
// BACnet Profile Example - B-LD (BACnet Lighting Device) - C++
//
// This example implements the BACnet "B-LD" (Lighting Device) profile with the
// CAS BACnet Stack. It is the B-ASC (Application Specific Controller) example
// plus the object the profile exists for: a Lighting Output.
//
// A B-LD (ANSI/ASHRAE 135, Annex L.11) is a light: a device that a lighting
// system dims, fades, and switches over BACnet. It must support:
//
//     DS-RP-B     - respond to ReadProperty requests,
//     DS-WP-B     - allow other devices to WriteProperty its objects,
//     DS-LO-B     - present a Lighting Output object (NEW - the defining BIBB).
//                   (The profile says "DS-BLO-B *or* DS-LO-B" - a Binary Lighting
//                   Output would satisfy it too. We implement the Lighting Output,
//                   the dimmable one, because it is the richer of the two and the
//                   one that carries Lighting_Command. Only one is required, so a
//                   faithful example implements only one.)
//     DM-DDB-B    - answer Who-Is with I-Am      (handled by the stack),
//     DM-DOB-B    - answer Who-Has with I-Have   (handled by the stack),
//     DM-DCC-B    - respond to DeviceCommunicationControl,
//     DM-TS-B     - accept TimeSynchronization (NEW): a lighting system tells the
//                   device what time it is, so scheduled scenes line up. (The
//                   profile says "DM-TS-B or DM-UTC-B"; we do local TimeSync.)
//
// It does NOT require COV, alarms, scheduling, or trending, so this example leaves
// those off. (A device that SUPERVISES other lights - writing to them - is a
// B-LS, a different profile with its own example.)
//
// HOW A LIGHTING OUTPUT IS DRIVEN. There are two ways, and the example serves
// both because BACnet requires both:
//
//   1. Present_Value (REAL, 0.0-100.0 percent) is COMMANDABLE, exactly like the
//      Analog Output in B-SA: a 16-slot Priority_Array plus a Relinquish_Default.
//      Writing it jumps the light straight to a level.
//
//   2. Lighting_Command is the interesting one, and it is what makes a light a
//      light rather than a generic analog output. It is a CONSTRUCTED value - a
//      BACnetLightingCommand SEQUENCE - carrying an operation (fadeTo, rampTo,
//      stepUp, warn, stop, ...) plus the optional parameters that operation needs
//      (target-level, ramp-rate, step-increment, fade-time, priority). Writing it
//      tells the light HOW to get somewhere, not just where: "fade to 75% over
//      3 seconds" rather than "be 75% now".
//
//      The application never encodes or decodes that SEQUENCE. It hands the stack
//      the fields as plain numbers through RegisterCallbackGetPropertyLightingCommand
//      and receives them the same way through RegisterCallbackSetPropertyLightingCommand;
//      the stack does all the BACnet encoding. See section 2c.
//
// The device keeps the same objects as B-ASC / B-SA and adds the Lighting Output.
// Each object has a colour name (the convention shared across this example series):
//
//     Device 389016            "Rainbow"     (instance configurable with --deviceID)
//     Analog Input  1          "Bronze"      (REAL, degrees Celsius; read-only)
//     Binary Input  1          "Emerald"     (active / inactive; read-only)
//     Multi-State Input 1      "Hot Pink"    (state 1..3; read-only)
//     Analog Output 1          "Chartreuse"  (REAL setpoint; WRITABLE, commandable)
//     Binary Output 1          "Fuchsia"     (active / inactive; WRITABLE, commandable)
//     Multi-State Output 1     "Indigo"      (state 1..3; WRITABLE, commandable)
//     Lighting Output 1        "Jade"        (REAL 0-100%; WRITABLE, commandable,
//                                             + Lighting_Command - the B-LD addition)
//     Network Port 1           "Vermilion"   (the BACnet/IP port - required)
//
// Output objects are COMMANDABLE: their Present_Value is driven by a 16-slot
// BACnet Priority_Array. A WriteProperty(Present_Value, value, priority) sets a
// slot; writing NULL relinquishes it; the stack reports the highest-priority
// non-null slot (or Relinquish_Default) as the effective Present_Value. The app
// stores the priority array (see the Commandable struct below) and serves it; the
// stack computes Present_Value from it.
//
// To be a conformant BACnet device (Protocol_Revision 24) each object must
// expose its full set of REQUIRED properties. Most are generated by the stack
// (Object_Identifier, Object_Type, Status_Flags, Event_State, Object_List,
// Protocol_*). The handful that the application must supply are served by the
// Get*Property callbacks below, and a few are turned on with SetPropertyEnabled.
//
// Interactive keys (handled by the shared helper): h = help, q = quit,
// up/down = nudge Analog Input 1 by +/-1.1. Command line: --port <n>,
// --deviceID <n>.
//
// All the UDP/stack plumbing lives in common/CASExampleHelper so this file can
// stay focused on the BACnet logic.
// =============================================================================

#include "CASExampleHelper.h"
#include "CASBACnetStackExampleConstants.h"
#include "CASBACnetStackDLL.h" // the CAS BACnet Stack C API (BACnetStack_*)

#include <stdio.h>
#include <string.h>

#if defined(_WIN32)
#include <windows.h> // Sleep()
#else
#include <unistd.h>  // usleep()
#endif

using namespace CASBACnetStackExampleConstants;

// -----------------------------------------------------------------------------
// 0. Lighting constants used only by this example
//
// The shared common/CASBACnetStackExampleConstants.h carries the values every
// example needs. The lighting values below are specific to this profile, so they
// live here - same style, citing the stack header that owns the full enumeration.
// -----------------------------------------------------------------------------

// -- Lighting Output object type (Object_Type enumeration) -------------------
//    Full list: submodules/cas-bacnet-stack/source/BACnetObjectType.h
static const uint16_t OBJECT_TYPE_LIGHTING_OUTPUT = 54;

// -- Lighting Output property identifiers (Property_Identifier enumeration) ---
//    Full list: submodules/cas-bacnet-stack/source/BACnetPropertyIdentifier.h
static const uint32_t PROPERTY_IDENTIFIER_TRACKING_VALUE = 164;
static const uint32_t PROPERTY_IDENTIFIER_BLINK_WARN_ENABLE = 373;
static const uint32_t PROPERTY_IDENTIFIER_DEFAULT_FADE_TIME = 374;
static const uint32_t PROPERTY_IDENTIFIER_DEFAULT_RAMP_RATE = 375;
static const uint32_t PROPERTY_IDENTIFIER_DEFAULT_STEP_INCREMENT = 376;
static const uint32_t PROPERTY_IDENTIFIER_EGRESS_TIME = 377;
static const uint32_t PROPERTY_IDENTIFIER_IN_PROGRESS = 378;
static const uint32_t PROPERTY_IDENTIFIER_LIGHTING_COMMAND = 380;
static const uint32_t PROPERTY_IDENTIFIER_LIGHTING_COMMAND_DEFAULT_PRIORITY = 381;
static const uint32_t PROPERTY_IDENTIFIER_EGRESS_ACTIVE = 386;

// -- BACnetLightingOperation - what a Lighting_Command tells the light to DO --
//    Full list: submodules/cas-bacnet-stack/source/BACnetLightingOperation.h
static const uint32_t LIGHTING_OPERATION_NONE = 0;
static const uint32_t LIGHTING_OPERATION_FADE_TO = 1;
static const uint32_t LIGHTING_OPERATION_RAMP_TO = 2;
static const uint32_t LIGHTING_OPERATION_STEP_UP = 3;
static const uint32_t LIGHTING_OPERATION_STEP_DOWN = 4;
static const uint32_t LIGHTING_OPERATION_STOP = 10;

// -- BACnetLightingInProgress - what the light is doing right now -------------
//    Full list: submodules/cas-bacnet-stack/source/BACnetLightingInProgress.h
static const uint32_t LIGHTING_IN_PROGRESS_IDLE = 0;
static const uint32_t LIGHTING_IN_PROGRESS_FADE_ACTIVE = 1;
static const uint32_t LIGHTING_IN_PROGRESS_RAMP_ACTIVE = 2;

// NOTE: ENGINEERING_UNITS_PERCENT and SERVICE_TIME_SYNCHRONIZATION used to be
// declared here too. They now live in common/CASBACnetStackExampleConstants.h
// (which as of common/ v1.2.0 is the real series-wide union), so declaring them
// again here would be an ambiguous symbol. Only values that are genuinely
// specific to THIS profile belong in this block - see the runbook's note on
// where profile-specific constants go.

// -----------------------------------------------------------------------------
// 1. Example + device configuration
// -----------------------------------------------------------------------------
static const char* APP_NAME = "BACnet B-LD (Lighting Device) Example - C++";
static const char* APP_VERSION = "1.0.0";

// The device instance. BACnet requires this to be configurable, so it defaults
// to 389016 and can be overridden on the command line with --deviceID.
static uint32_t g_deviceInstance = 389016;

// ---- Device identity: CHANGE ALL OF THIS BEFORE YOU SHIP --------------------
// Everything in this block is read by clients and shown to the operator in every
// discovery tool on the network. Left as-is, your product will appear on a real
// site announcing itself as a Chipkin demo. None of it is cosmetic:
// Object_Name must be unique across the BACnet internetwork, and Model_Name /
// Vendor_Identifier are what a building operator uses to identify your device.
// -----------------------------------------------------------------------------

// Your BACnet Vendor Identifier. 389 = Chipkin Automation Systems; change this
// to YOUR company's vendor ID before shipping a product. Vendor IDs are assigned
// by ASHRAE - request one (free) at https://bacnet.org/assigned-vendor-ids/.
// Update VENDOR_NAME below to match.
static const uint32_t VENDOR_IDENTIFIER = 389;
static const char* DEVICE_NAME = "Rainbow";
static const char* DEVICE_DESCRIPTION =
    "Chipkin CAS BACnet Stack Example - B-LD (Application Specific Controller) "
    "profile. Demonstrates DS-RP-B + DS-WP-B + DM-DCC-B: ReadProperty, "
    "WriteProperty, and DeviceCommunicationControl with read-only sensor inputs "
    "and commandable outputs.";

// Device identity strings (read by clients, and used to populate I-Am).
static const char* VENDOR_NAME = "Chipkin Automation Systems";
static const char* MODEL_NAME = "CAS BACnet Stack Example - B-LD";

// DeviceCommunicationControl password. A management station may include a password
// with a DeviceCommunicationControl (or ReinitializeDevice) request; the device
// accepts the command only if it matches. Set to NULL/empty to accept any request
// (no password required). Change this to your device's secret before shipping.
static const char* DCC_PASSWORD = "";  // "" = no password required
static const char* FIRMWARE_REVISION = "1.0.0";
static const char* APPLICATION_SOFTWARE_VERSION = "1.0.0";

// The sensor objects (all instance 1) and their colour names.
static const uint32_t ANALOG_INPUT_INSTANCE = 1;       // "Bronze"
static const uint32_t BINARY_INPUT_INSTANCE = 1;       // "Emerald"
static const uint32_t MULTI_STATE_INPUT_INSTANCE = 1;  // "Hot Pink"
static const uint32_t MULTI_STATE_INPUT_NUMBER_OF_STATES = 3;

// The Network Port object - every BACnet device must have one. It represents
// the BACnet/IP port this device communicates on.
static const uint32_t NETWORK_PORT_INSTANCE = 1;       // "Vermilion"
static const uint32_t MAX_APDU_LENGTH = 1476;          // BACnet/IP APDU length

// BACnet/IP addressing the Network Port reports. The IP address and subnet mask
// are filled in at start-up from the host's primary interface; the gateway is
// left unset (0.0.0.0) for this example. The stack also uses IP_Address +
// BACnet_IP_UDP_Port to build the port's MAC_Address automatically.
static uint8_t g_ipAddress[4] = { 0, 0, 0, 0 };
static uint8_t g_ipSubnetMask[4] = { 0, 0, 0, 0 };
static uint8_t g_ipDefaultGateway[4] = { 0, 0, 0, 0 };
static uint16_t g_bacnetIpUdpPort = 47808;

// Analog Input 1's live present value (degrees Celsius). Starts at 21.5 and is
// nudged by the up/down arrow keys. A real sensor would update this from
// hardware instead.
static float g_analogInput1Value = 21.5f;

// The commandable OUTPUT objects (all instance 1) and their colour names. These
// are what make this a B-SA actuator: clients drive them with WriteProperty.
static const uint32_t ANALOG_OUTPUT_INSTANCE = 1;        // "Chartreuse"
static const uint32_t BINARY_OUTPUT_INSTANCE = 1;        // "Fuchsia"
static const uint32_t MULTI_STATE_OUTPUT_INSTANCE = 1;   // "Indigo"
static const uint32_t MULTI_STATE_OUTPUT_NUMBER_OF_STATES = 3;
static const uint32_t BACNET_PRIORITY_ARRAY_SIZE = 16;

// A BACnet commandable value: a 16-slot Priority_Array plus a Relinquish_Default.
// Each slot is either null (relinquished) or holds a commanded value. A real
// device would map the resolved Present_Value onto its physical output; here we
// just store the commands. The values are kept as double and cast per object
// type (REAL for AO, 0/1 for BO, state number for MSO).
struct Commandable {
    bool isSet[16];          // is slot i (1..16) commanded?
    double value[16];        // the commanded value at slot i
    double relinquishDefault; // used when every slot is null
};

// The { { false }, { 0 }, default } initializer zero-fills all 16 slots of isSet
// and value (C++ aggregate rules: the remaining elements are value-initialized),
// so every priority slot starts null and Present_Value reports relinquishDefault.
static Commandable g_analogOutput = { { false }, { 0 }, 20.0 }; // setpoint, default 20.0 C
static Commandable g_binaryOutput = { { false }, { 0 }, 0.0 };  // default inactive (0)
static Commandable g_multiStateOutput = { { false }, { 0 }, 1.0 }; // default state 1

// --- The Lighting Output (the B-LD addition) ---------------------------------
static const uint32_t LIGHTING_OUTPUT_INSTANCE = 1;      // "Jade"

// Its Present_Value is commandable exactly like the Analog Output above - a level
// in percent. Relinquish_Default 0.0 means "when nothing commands this light, it
// is off", which is the safe resting state for a luminaire.
static Commandable g_lightingOutput = { { false }, { 0 }, 0.0 };

// The Lighting Output's REQUIRED scalar properties. A real luminaire would drive
// its dimming hardware from these; here they are the device's configuration.
//   Default_Fade_Time        - fade duration (ms) used when a fadeTo omits fade-time
//   Default_Ramp_Rate        - percent per second used when a rampTo omits ramp-rate
//   Default_Step_Increment   - percent used when a stepUp/stepDown omits step-increment
//   Egress_Time              - the blink-warn "get out of the room" period, in SECONDS
//   Lighting_Command_Default_Priority - the priority a Lighting_Command writes at
//                              when it does not name one (BACnet default is 16)
static const uint32_t LIGHTING_DEFAULT_FADE_TIME = 3000;      // 3.0 s, in milliseconds
static const float LIGHTING_DEFAULT_RAMP_RATE = 10.0f;        // 10 % per second
static const float LIGHTING_DEFAULT_STEP_INCREMENT = 5.0f;    // 5 %
static const uint32_t LIGHTING_EGRESS_TIME = 30;              // 30 s
static const uint32_t LIGHTING_COMMAND_DEFAULT_PRIORITY = 16;

// The last Lighting_Command a client wrote. Reading Lighting_Command reports back
// what the light was last told to do, so we remember it. A real device would ALSO
// be running the fade/ramp this describes; this example stores the command and
// reports the resulting level, which is what makes the read/write pair legible
// without simulating dimming hardware.
struct LightingCommandState {
    uint32_t operation;
    bool useTargetLevel;   float targetLevel;
    bool useRampRate;      float rampRate;
    bool useStepIncrement; float stepIncrement;
    bool useFadeTime;      uint32_t fadeTime;
    bool usePriority;      uint32_t priority;
};

// Starts as `none` - the light has not been commanded yet. `none` is a real
// BACnetLightingOperation value (0), not a placeholder: it is what a Lighting
// Output reports before anything has driven it.
static LightingCommandState g_lightingCommand = {
    LIGHTING_OPERATION_NONE,
    false, 0.0f, false, 0.0f, false, 0.0f, false, 0, false, 0
};

// Is the light mid-fade / mid-ramp? A real device would set this while its dimming
// hardware is moving and clear it on arrival. This example completes every command
// instantly, so it reports the honest answer: idle.
static uint32_t g_lightingInProgress = LIGHTING_IN_PROGRESS_IDLE;

// A WriteProperty to a commandable Present_Value carries a priority 1..16. When a
// client omits it, BACnet uses 16 (the lowest priority) - so normalise anything
// out of range to 16, matching the stack's own behaviour.
static uint8_t EffectivePriority(uint8_t priority) {
    return (priority >= 1 && priority <= BACNET_PRIORITY_ARRAY_SIZE) ? priority : 16;
}

// Store a commanded value at a priority slot (a WriteProperty of a value).
static void CommandWrite(Commandable* c, uint8_t priority, double value) {
    const uint8_t p = EffectivePriority(priority);
    c->isSet[p - 1] = true;
    c->value[p - 1] = value;
}

// Relinquish (clear) a priority slot - i.e. a WriteProperty of NULL.
static void CommandRelinquish(Commandable* c, uint8_t priority) {
    const uint8_t p = EffectivePriority(priority);
    c->isSet[p - 1] = false;
}

// Resolve which Commandable an (objectType, objectInstance) maps to, or NULL.
static Commandable* GetCommandable(uint16_t objectType, uint32_t objectInstance) {
    if (objectType == OBJECT_TYPE_ANALOG_OUTPUT && objectInstance == ANALOG_OUTPUT_INSTANCE) {
        return &g_analogOutput;
    }
    if (objectType == OBJECT_TYPE_BINARY_OUTPUT && objectInstance == BINARY_OUTPUT_INSTANCE) {
        return &g_binaryOutput;
    }
    if (objectType == OBJECT_TYPE_MULTI_STATE_OUTPUT && objectInstance == MULTI_STATE_OUTPUT_INSTANCE) {
        return &g_multiStateOutput;
    }
    // The Lighting Output is commandable in exactly the same way as the Analog
    // Output - a REAL level resolved from the Priority_Array. Adding it here is all
    // it takes to give it the whole commandable mechanism.
    if (objectType == OBJECT_TYPE_LIGHTING_OUTPUT && objectInstance == LIGHTING_OUTPUT_INSTANCE) {
        return &g_lightingOutput;
    }
    return NULL;
}

// Resolve the light's current level the way the stack does: highest-priority
// commanded slot, else Relinquish_Default. Used to serve Tracking_Value and to
// print the level - the stack serves Present_Value itself.
static float ResolveLightingLevel(const Commandable* c) {
    for (uint32_t i = 0; i < BACNET_PRIORITY_ARRAY_SIZE; i++) {
        if (c->isSet[i]) {
            return (float)c->value[i];
        }
    }
    return (float)c->relinquishDefault;
}

// A human-readable name for a BACnetLightingOperation, for the console log.
static const char* LightingOperationName(uint32_t operation) {
    switch (operation) {
        case LIGHTING_OPERATION_NONE:      return "none";
        case LIGHTING_OPERATION_FADE_TO:   return "fadeTo";
        case LIGHTING_OPERATION_RAMP_TO:   return "rampTo";
        case LIGHTING_OPERATION_STEP_UP:   return "stepUp";
        case LIGHTING_OPERATION_STEP_DOWN: return "stepDown";
        case LIGHTING_OPERATION_STOP:      return "stop";
        default:                           return "(other)";
    }
}

// Is this read a single Priority_Array element (Priority_Array[1..16])? If so,
// report whether that slot is commanded (*slotIsSet) and its value (*slotValue).
// The typed Get callbacks use this to serve a commandable object's Priority_Array
// and to let the stack compute Present_Value from the highest non-null slot.
static bool ReadPrioritySlot(const Commandable* c, uint32_t propertyIdentifier,
                             bool useArrayIndex, uint32_t propertyArrayIndex,
                             bool* slotIsSet, double* slotValue) {
    if (propertyIdentifier != PROPERTY_IDENTIFIER_PRIORITY_ARRAY || !useArrayIndex ||
        propertyArrayIndex < 1 || propertyArrayIndex > BACNET_PRIORITY_ARRAY_SIZE) {
        return false;
    }
    *slotIsSet = c->isSet[propertyArrayIndex - 1];
    *slotValue = c->value[propertyArrayIndex - 1];
    return true;
}

// -----------------------------------------------------------------------------
// 2. Property "get" callbacks
//
// The stack calls these when a client reads a property. For each data type the
// stack uses a separate callback. We return true (and fill *value) when we
// recognise the (object, property) pair, and false otherwise so the stack
// answers with the proper BACnet error. Note what false does NOT mean: it is not
// "the read failed", and it is not "the value is null". It means "not mine" -
// you are declining to answer, and the stack turns that into a BACnet error.
//
// ADDING AN OBJECT? READ THIS FIRST.
// These callbacks are not uniformly strict, and the difference bites:
//   - GetPropertyReal / GetPropertyEnumerated / GetPropertyUnsignedInteger match
//     on object type AND INSTANCE (directly, or via GetCommandable(), which
//     looks up the exact type+instance pair). A new instance falls through every
//     one of those checks and gets an error.
//   - GetPropertyBool serves Out_Of_Service on object TYPE ONLY, so a new
//     instance of an existing type gets Out_Of_Service for free.
// So a half-added object answers Out_Of_Service but errors on Present_Value and
// Units - i.e. it looks alive on a scan and is non-conformant. When you add an
// instance, walk EVERY callback below, then read back every required property of
// the new object.
// -----------------------------------------------------------------------------

// REAL (floating point) - the Analog Input's Present_Value.
bool GetPropertyReal(const uint32_t deviceInstance, const uint16_t objectType,
                     const uint32_t objectInstance, const uint32_t propertyIdentifier,
                     float* value, const bool useArrayIndex,
                     const uint32_t propertyArrayIndex) {
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    if (objectType == OBJECT_TYPE_ANALOG_INPUT &&
        objectInstance == ANALOG_INPUT_INSTANCE &&
        propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
        // ON REAL HARDWARE: return the live sensor reading here. Read it from a
        // cached variable that your hardware updates (as g_analogInput1Value is),
        // NOT directly from a slow/blocking device (I2C, SPI, ADC conversion):
        // this callback runs on the BACnetStack_Tick() thread, so blocking it
        // delays all BACnet processing. Sample the sensor on a timer/another
        // thread and just hand back the latest value from here.
        *value = g_analogInput1Value;
        return true;
    }
    // Analog Output (commandable): serve its Priority_Array slots and
    // Relinquish_Default. The stack reads each slot to compute Present_Value and
    // to answer a ReadProperty of the whole array. For a null (relinquished) slot
    // we return false - the stack then takes the "slot is null" answer from
    // GetPropertyBool below.
    const Commandable* c = GetCommandable(objectType, objectInstance);
    // Both the Analog Output and the Lighting Output carry a REAL Present_Value, so
    // both serve their Priority_Array slots + Relinquish_Default through this one
    // callback - the commandable mechanism does not care what the object is.
    if (c != NULL && (objectType == OBJECT_TYPE_ANALOG_OUTPUT ||
                      objectType == OBJECT_TYPE_LIGHTING_OUTPUT)) {
        bool slotIsSet = false;
        double slotValue = 0.0;
        if (ReadPrioritySlot(c, propertyIdentifier, useArrayIndex, propertyArrayIndex,
                             &slotIsSet, &slotValue)) {
            if (!slotIsSet) {
                return false;
            }
            *value = (float)slotValue;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_RELINQUISH_DEFAULT) {
            *value = (float)c->relinquishDefault;
            return true;
        }
    }

    // --- The Lighting Output's REQUIRED REAL properties ----------------------
    if (objectType == OBJECT_TYPE_LIGHTING_OUTPUT && objectInstance == LIGHTING_OUTPUT_INSTANCE) {
        switch (propertyIdentifier) {
            case PROPERTY_IDENTIFIER_TRACKING_VALUE:
                // Tracking_Value is what the light ACTUALLY is, as opposed to what it
                // was commanded to be (Present_Value). They differ mid-fade on real
                // hardware. This example completes commands instantly, so they agree -
                // a real driver would report its measured//live level here.
                *value = ResolveLightingLevel(&g_lightingOutput);
                return true;
            case PROPERTY_IDENTIFIER_DEFAULT_RAMP_RATE:
                *value = LIGHTING_DEFAULT_RAMP_RATE;
                return true;
            case PROPERTY_IDENTIFIER_DEFAULT_STEP_INCREMENT:
                *value = LIGHTING_DEFAULT_STEP_INCREMENT;
                return true;
            default:
                break;
        }
    }
    return false;
}

// ENUMERATED - the Binary Input's Present_Value (0 = inactive, 1 = active) and
// the Analog Input's Units (degrees Celsius).
bool GetPropertyEnumerated(const uint32_t deviceInstance, const uint16_t objectType,
                           const uint32_t objectInstance, const uint32_t propertyIdentifier,
                           uint32_t* value, const bool useArrayIndex,
                           const uint32_t propertyArrayIndex) {
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    if (objectType == OBJECT_TYPE_BINARY_INPUT &&
        objectInstance == BINARY_INPUT_INSTANCE) {
        if (propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
            *value = 1; // active
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_POLARITY) {
            *value = POLARITY_NORMAL; // required property of a Binary Input
            return true;
        }
    }
    // Binary Output (commandable): Present_Value is an enumerated active/inactive
    // driven through the Priority_Array. Serve the array slots and Relinquish_Default
    // (plus its required Polarity).
    const Commandable* c = GetCommandable(objectType, objectInstance);
    if (c != NULL && objectType == OBJECT_TYPE_BINARY_OUTPUT) {
        bool slotIsSet = false;
        double slotValue = 0.0;
        if (ReadPrioritySlot(c, propertyIdentifier, useArrayIndex, propertyArrayIndex,
                             &slotIsSet, &slotValue)) {
            if (!slotIsSet) {
                return false;
            }
            *value = (uint32_t)slotValue;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_RELINQUISH_DEFAULT) {
            *value = (uint32_t)c->relinquishDefault;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_POLARITY) {
            *value = POLARITY_NORMAL; // required property of a Binary Output
            return true;
        }
    }
    if (objectType == OBJECT_TYPE_ANALOG_INPUT &&
        objectInstance == ANALOG_INPUT_INSTANCE &&
        propertyIdentifier == PROPERTY_IDENTIFIER_UNITS) {
        *value = ENGINEERING_UNITS_DEGREES_CELSIUS;
        return true;
    }
    if (objectType == OBJECT_TYPE_NETWORK_PORT &&
        objectInstance == NETWORK_PORT_INSTANCE &&
        propertyIdentifier == PROPERTY_IDENTIFIER_BACNET_IP_MODE) {
        *value = BACNET_IP_MODE_NORMAL; // not foreign-device, not BBMD
        return true;
    }

    // --- The Lighting Output's REQUIRED enumerated properties ----------------
    if (objectType == OBJECT_TYPE_LIGHTING_OUTPUT && objectInstance == LIGHTING_OUTPUT_INSTANCE) {
        if (propertyIdentifier == PROPERTY_IDENTIFIER_IN_PROGRESS) {
            // What the light is doing right now: idle / fadeActive / rampActive.
            // A real driver would report fadeActive while its hardware is moving and
            // flip to idle on arrival; this example completes instantly, so idle.
            *value = g_lightingInProgress;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_UNITS) {
            // A Lighting Output's level is a percentage.
            *value = ENGINEERING_UNITS_PERCENT;
            return true;
        }
    }
    return false;
}

// UNSIGNED INTEGER - the Multi-State Input's Present_Value, and the Device's
// Vendor_Identifier (the stack also uses Vendor_Identifier to build I-Am).
bool GetPropertyUnsignedInteger(const uint32_t deviceInstance, const uint16_t objectType,
                                const uint32_t objectInstance, const uint32_t propertyIdentifier,
                                uint32_t* value, const bool useArrayIndex,
                                const uint32_t propertyArrayIndex) {
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    if (objectType == OBJECT_TYPE_MULTI_STATE_INPUT &&
        objectInstance == MULTI_STATE_INPUT_INSTANCE) {
        if (propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
            *value = 1; // state 1 (valid range is 1..Number_Of_States)
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_NUMBER_OF_STATES) {
            *value = MULTI_STATE_INPUT_NUMBER_OF_STATES; // required property
            return true;
        }
        // State_Text is an array. The stack asks for its LENGTH here (array
        // index 0) before reading each element via GetPropertyCharString.
        if (propertyIdentifier == PROPERTY_IDENTIFIER_STATE_TEXT &&
            useArrayIndex && propertyArrayIndex == 0) {
            *value = MULTI_STATE_INPUT_NUMBER_OF_STATES;
            return true;
        }
    }
    if (objectType == OBJECT_TYPE_DEVICE && objectInstance == g_deviceInstance &&
        propertyIdentifier == PROPERTY_IDENTIFIER_VENDOR_IDENTIFIER) {
        *value = VENDOR_IDENTIFIER;
        return true;
    }
    if (objectType == OBJECT_TYPE_NETWORK_PORT && objectInstance == NETWORK_PORT_INSTANCE) {
        if (propertyIdentifier == PROPERTY_IDENTIFIER_APDU_LENGTH) {
            *value = MAX_APDU_LENGTH;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_REFERENCE_PORT) {
            *value = NETWORK_PORT_REFERENCE_PORT_NONE;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_BACNET_IP_UDP_PORT) {
            *value = g_bacnetIpUdpPort;
            return true;
        }
    }
    // Multi-State Output (commandable): Present_Value is an unsigned state number
    // driven through the Priority_Array. Serve the array slots, Relinquish_Default,
    // and the required Number_Of_States.
    const Commandable* c = GetCommandable(objectType, objectInstance);
    if (c != NULL && objectType == OBJECT_TYPE_MULTI_STATE_OUTPUT) {
        bool slotIsSet = false;
        double slotValue = 0.0;
        if (ReadPrioritySlot(c, propertyIdentifier, useArrayIndex, propertyArrayIndex,
                             &slotIsSet, &slotValue)) {
            if (!slotIsSet) {
                return false;
            }
            *value = (uint32_t)slotValue;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_RELINQUISH_DEFAULT) {
            *value = (uint32_t)c->relinquishDefault;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_NUMBER_OF_STATES) {
            *value = MULTI_STATE_OUTPUT_NUMBER_OF_STATES;
            return true;
        }
    }

    // --- The Lighting Output's REQUIRED unsigned properties ------------------
    // These are the light's dimming defaults: what it does when a Lighting_Command
    // names an operation but omits that operation's parameter (cl. 12.54.9). E.g. a
    // fadeTo with no fade-time fades over Default_Fade_Time.
    if (objectType == OBJECT_TYPE_LIGHTING_OUTPUT && objectInstance == LIGHTING_OUTPUT_INSTANCE) {
        switch (propertyIdentifier) {
            case PROPERTY_IDENTIFIER_DEFAULT_FADE_TIME:
                *value = LIGHTING_DEFAULT_FADE_TIME; // milliseconds
                return true;
            case PROPERTY_IDENTIFIER_EGRESS_TIME:
                *value = LIGHTING_EGRESS_TIME;       // seconds - note: NOT milliseconds
                return true;
            case PROPERTY_IDENTIFIER_LIGHTING_COMMAND_DEFAULT_PRIORITY:
                *value = LIGHTING_COMMAND_DEFAULT_PRIORITY;
                return true;
            default:
                break;
        }
    }
    return false;
}

// BOOLEAN - Out_Of_Service is a required property of every input object and of
// the Network Port. This is a read-only sensor, so nothing is ever out of
// service: always false.
bool GetPropertyBool(const uint32_t deviceInstance, const uint16_t objectType,
                     const uint32_t objectInstance, const uint32_t propertyIdentifier,
                     bool* value, const bool useArrayIndex,
                     const uint32_t propertyArrayIndex) {
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    // Commandable outputs: the stack asks "is this Priority_Array slot null?" with
    // the boolean getter. Answer true (1) for a relinquished slot, false (0) for a
    // commanded one. This is how the stack knows which slots to skip when computing
    // Present_Value and how it encodes the NULLs in a ReadProperty of the array.
    const Commandable* c = GetCommandable(objectType, objectInstance);
    if (c != NULL && propertyIdentifier == PROPERTY_IDENTIFIER_PRIORITY_ARRAY &&
        useArrayIndex && propertyArrayIndex >= 1 &&
        propertyArrayIndex <= BACNET_PRIORITY_ARRAY_SIZE) {
        *value = !c->isSet[propertyArrayIndex - 1];
        return true;
    }
    // Out_Of_Service is a required property of every input and output object and of
    // the Network Port. This example never takes anything out of service: false.
    if (propertyIdentifier == PROPERTY_IDENTIFIER_OUT_OF_SERVICE &&
        (objectType == OBJECT_TYPE_ANALOG_INPUT ||
         objectType == OBJECT_TYPE_BINARY_INPUT ||
         objectType == OBJECT_TYPE_MULTI_STATE_INPUT ||
         objectType == OBJECT_TYPE_ANALOG_OUTPUT ||
         objectType == OBJECT_TYPE_BINARY_OUTPUT ||
         objectType == OBJECT_TYPE_MULTI_STATE_OUTPUT ||
         objectType == OBJECT_TYPE_LIGHTING_OUTPUT ||
         objectType == OBJECT_TYPE_NETWORK_PORT)) {
        *value = false;
        return true;
    }

    // --- The Lighting Output's REQUIRED boolean properties -------------------
    if (objectType == OBJECT_TYPE_LIGHTING_OUTPUT && objectInstance == LIGHTING_OUTPUT_INSTANCE) {
        if (propertyIdentifier == PROPERTY_IDENTIFIER_BLINK_WARN_ENABLE) {
            // Blink-warn is the "the lights are about to go out" flash that gives
            // people Egress_Time to leave. Enabled here so the property is meaningful.
            *value = true;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_EGRESS_ACTIVE) {
            // True only while the egress timer is actually running (i.e. between a
            // warn command and the lights going off). Nothing drives it in this
            // example, so it is honestly false.
            *value = false;
            return true;
        }
    }
    return false;
}

// OCTET STRING - the Network Port's BACnet/IP addressing. The stack cannot know
// the host's IP, so the application must supply IP_Address and IP_Subnet_Mask
// (and IP_Default_Gateway). Each is four octets. The stack also reads IP_Address
// (with BACnet_IP_UDP_Port) to build the port's six-octet MAC_Address.
bool GetPropertyOctetString(const uint32_t deviceInstance, const uint16_t objectType,
                            const uint32_t objectInstance, const uint32_t propertyIdentifier,
                            uint8_t* value, uint32_t* valueElementCount,
                            const uint32_t maxElementCount, const bool useArrayIndex,
                            const uint32_t propertyArrayIndex) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    if (deviceInstance != g_deviceInstance ||
        objectType != OBJECT_TYPE_NETWORK_PORT ||
        objectInstance != NETWORK_PORT_INSTANCE ||
        maxElementCount < 4) {
        return false;
    }
    const uint8_t* source = NULL;
    switch (propertyIdentifier) {
        case PROPERTY_IDENTIFIER_IP_ADDRESS:         source = g_ipAddress; break;
        case PROPERTY_IDENTIFIER_IP_SUBNET_MASK:     source = g_ipSubnetMask; break;
        case PROPERTY_IDENTIFIER_IP_DEFAULT_GATEWAY: source = g_ipDefaultGateway; break;
        default: return false;
    }
    memcpy(value, source, 4);
    *valueElementCount = 4;
    return true;
}

// Small helper: copy a C string into the stack's character-string buffer and
// set the element count + encoding. Returns true (so callers can `return`).
static bool ReturnCharacterString(const char* text, char* value,
                                  uint32_t* valueElementCount,
                                  const uint32_t maxElementCount,
                                  uint8_t* encodingType) {
    uint32_t length = (uint32_t)strlen(text);
    if (length > maxElementCount) {
        length = maxElementCount;
    }
    memcpy(value, text, length);
    *valueElementCount = length;
    *encodingType = CHARACTER_STRING_ENCODING_UTF8;
    return true;
}

// CHARACTER STRING - Object_Name for each object, and the device Description.
bool GetPropertyCharString(const uint32_t deviceInstance, const uint16_t objectType,
                           const uint32_t objectInstance, const uint32_t propertyIdentifier,
                           char* value, uint32_t* valueElementCount,
                           const uint32_t maxElementCount, uint8_t* encodingType,
                           const bool useArrayIndex, const uint32_t propertyArrayIndex) {
    if (deviceInstance != g_deviceInstance) {
        return false;
    }

    // State_Text (optional) - one label per state of the Multi-State Input. It is
    // a BACnet array, so the stack asks for one element at a time by index
    // (1..Number_Of_States). Present_Value 1 -> "On", 2 -> "Off", 3 -> "Auto".
    if (objectType == OBJECT_TYPE_MULTI_STATE_INPUT &&
        objectInstance == MULTI_STATE_INPUT_INSTANCE &&
        propertyIdentifier == PROPERTY_IDENTIFIER_STATE_TEXT && useArrayIndex) {
        static const char* const stateText[] = { "On", "Off", "Auto" };
        if (propertyArrayIndex >= 1 && propertyArrayIndex <= MULTI_STATE_INPUT_NUMBER_OF_STATES) {
            return ReturnCharacterString(stateText[propertyArrayIndex - 1], value,
                                         valueElementCount, maxElementCount, encodingType);
        }
        return false;
    }

    // Object_Name - the colour name for each object.
    if (propertyIdentifier == PROPERTY_IDENTIFIER_OBJECT_NAME) {
        if (objectType == OBJECT_TYPE_DEVICE && objectInstance == g_deviceInstance) {
            return ReturnCharacterString(DEVICE_NAME, value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_ANALOG_INPUT && objectInstance == ANALOG_INPUT_INSTANCE) {
            return ReturnCharacterString("Bronze", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_BINARY_INPUT && objectInstance == BINARY_INPUT_INSTANCE) {
            return ReturnCharacterString("Emerald", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_MULTI_STATE_INPUT && objectInstance == MULTI_STATE_INPUT_INSTANCE) {
            return ReturnCharacterString("Hot Pink", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_ANALOG_OUTPUT && objectInstance == ANALOG_OUTPUT_INSTANCE) {
            return ReturnCharacterString("Chartreuse", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_BINARY_OUTPUT && objectInstance == BINARY_OUTPUT_INSTANCE) {
            return ReturnCharacterString("Fuchsia", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_MULTI_STATE_OUTPUT && objectInstance == MULTI_STATE_OUTPUT_INSTANCE) {
            return ReturnCharacterString("Indigo", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_LIGHTING_OUTPUT && objectInstance == LIGHTING_OUTPUT_INSTANCE) {
            return ReturnCharacterString("Jade", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_NETWORK_PORT && objectInstance == NETWORK_PORT_INSTANCE) {
            return ReturnCharacterString("Vermilion", value, valueElementCount, maxElementCount, encodingType);
        }
    }

    // The remaining strings are all on the Device object - its identity, read
    // by clients and used to populate the device's I-Am / object list.
    if (objectType == OBJECT_TYPE_DEVICE && objectInstance == g_deviceInstance) {
        switch (propertyIdentifier) {
            case PROPERTY_IDENTIFIER_DESCRIPTION:
                return ReturnCharacterString(DEVICE_DESCRIPTION, value, valueElementCount, maxElementCount, encodingType);
            case PROPERTY_IDENTIFIER_VENDOR_NAME:
                return ReturnCharacterString(VENDOR_NAME, value, valueElementCount, maxElementCount, encodingType);
            case PROPERTY_IDENTIFIER_MODEL_NAME:
                return ReturnCharacterString(MODEL_NAME, value, valueElementCount, maxElementCount, encodingType);
            case PROPERTY_IDENTIFIER_FIRMWARE_REVISION:
                return ReturnCharacterString(FIRMWARE_REVISION, value, valueElementCount, maxElementCount, encodingType);
            case PROPERTY_IDENTIFIER_APPLICATION_SOFTWARE_VERSION:
                return ReturnCharacterString(APPLICATION_SOFTWARE_VERSION, value, valueElementCount, maxElementCount, encodingType);
            default:
                break;
        }
    }

    return false;
}

// -----------------------------------------------------------------------------
// 2b. Property "set" callbacks - the heart of B-SA (DS-WP-B)
//
// The stack calls these when a client sends WriteProperty to a commandable
// output's Present_Value. The value arrives already decoded into the matching
// data type, together with the priority (1..16) the client wrote at. We store it
// in the object's Priority_Array; the stack recomputes Present_Value from the
// array on the next read. A WriteProperty of NULL relinquishes a slot and arrives
// through SetPropertyNull instead.
//
// Return true when we accept the write; return false (optionally setting
// *errorCode) to reject it, and the stack answers with a BACnet Error-PDU.
// -----------------------------------------------------------------------------

// REAL write - Analog Output 1 (Chartreuse) Present_Value.
bool SetPropertyReal(const uint32_t deviceInstance, const uint16_t objectType,
                     const uint32_t objectInstance, const uint32_t propertyIdentifier,
                     const float value, const bool useArrayIndex,
                     const uint32_t propertyArrayIndex, const uint8_t priority,
                     uint32_t* errorCode) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    (void)errorCode;
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    Commandable* c = GetCommandable(objectType, objectInstance);
    if (c != NULL && objectType == OBJECT_TYPE_ANALOG_OUTPUT &&
        propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
        // An Analog Output accepts any REAL here. A real device that models the
        // optional Min_Pres_Value / Max_Pres_Value properties would reject an
        // out-of-band value with value-out-of-range, exactly as the Binary and
        // Multi-State Output setters below do for their fixed ranges:
        //     if (value < g_min || value > g_max) {
        //         *errorCode = ERROR_CODE_VALUE_OUT_OF_RANGE; return false;
        //     }
        CommandWrite(c, priority, (double)value);
        printf("WriteProperty: Analog Output 1 (Chartreuse) <- %.2f @ priority %u\n",
               value, EffectivePriority(priority));
        return true;
    }
    return false;
}

// ENUMERATED write - Binary Output 1 (Fuchsia) Present_Value (0/1).
bool SetPropertyEnumerated(const uint32_t deviceInstance, const uint16_t objectType,
                           const uint32_t objectInstance, const uint32_t propertyIdentifier,
                           const uint32_t value, const bool useArrayIndex,
                           const uint32_t propertyArrayIndex, const uint8_t priority,
                           uint32_t* errorCode) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    Commandable* c = GetCommandable(objectType, objectInstance);
    if (c != NULL && objectType == OBJECT_TYPE_BINARY_OUTPUT &&
        propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
        // A Binary Output's Present_Value is 0 (inactive) or 1 (active). Reject
        // anything else with value-out-of-range - validating the written value is
        // part of being a conformant DS-WP-B device.
        if (value > 1) {
            *errorCode = ERROR_CODE_VALUE_OUT_OF_RANGE;
            return false;
        }
        CommandWrite(c, priority, (double)value);
        printf("WriteProperty: Binary Output 1 (Fuchsia) <- %s @ priority %u\n",
               value ? "active" : "inactive", EffectivePriority(priority));
        return true;
    }
    return false;
}

// UNSIGNED write - Multi-State Output 1 (Indigo) Present_Value (state 1..3).
bool SetPropertyUnsignedInteger(const uint32_t deviceInstance, const uint16_t objectType,
                                const uint32_t objectInstance, const uint32_t propertyIdentifier,
                                const uint32_t value, const bool useArrayIndex,
                                const uint32_t propertyArrayIndex, const uint8_t priority,
                                uint32_t* errorCode) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    Commandable* c = GetCommandable(objectType, objectInstance);
    if (c != NULL && objectType == OBJECT_TYPE_MULTI_STATE_OUTPUT &&
        propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
        // A Multi-State Output's Present_Value is a state number in 1..Number_Of_States.
        // Reject anything outside that range with value-out-of-range.
        if (value < 1 || value > MULTI_STATE_OUTPUT_NUMBER_OF_STATES) {
            *errorCode = ERROR_CODE_VALUE_OUT_OF_RANGE;
            return false;
        }
        CommandWrite(c, priority, (double)value);
        printf("WriteProperty: Multi-State Output 1 (Indigo) <- state %u @ priority %u\n",
               value, EffectivePriority(priority));
        return true;
    }
    return false;
}

// NULL write - relinquish a commandable output's Present_Value at a priority. The
// stack routes a WriteProperty of NULL here (one callback for every data type).
bool SetPropertyNull(const uint32_t deviceInstance, const uint16_t objectType,
                     const uint32_t objectInstance, const uint32_t propertyIdentifier,
                     const bool useArrayIndex, const uint32_t propertyArrayIndex,
                     const uint8_t priority, uint32_t* errorCode) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    (void)errorCode;
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    Commandable* c = GetCommandable(objectType, objectInstance);
    if (c != NULL && propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
        CommandRelinquish(c, priority);
        printf("WriteProperty: relinquished %s %u @ priority %u\n",
               objectType == OBJECT_TYPE_ANALOG_OUTPUT ? "Analog Output" :
               objectType == OBJECT_TYPE_BINARY_OUTPUT ? "Binary Output" :
               "Multi-State Output",
               objectInstance, EffectivePriority(priority));
        return true;
    }
    return false;
}

// -----------------------------------------------------------------------------
// 2c. Lighting_Command callbacks - the heart of B-LD (DS-LO-B)
//
// Lighting_Command is a CONSTRUCTED property: a BACnetLightingCommand SEQUENCE
// carrying an operation plus the optional parameters that operation needs.
// Encoding and decoding it is the STACK's job - the application only ever handles
// plain numbers, through the two callbacks below. That is why there is no BACnet
// byte-twiddling anywhere in this file.
//
//     operation      - fadeTo / rampTo / stepUp / stepDown / warn / stop / ...
//     target-level   - REAL 0.0..100.0   (optional)
//     ramp-rate      - REAL % per second (optional)
//     step-increment - REAL %            (optional)
//     fade-time      - Unsigned ms       (optional)
//     priority       - Unsigned 1..16    (optional)
//
// Each optional field has a use* flag. On the GET side, setting it false omits
// the field from the SEQUENCE. On the SET side, false means the WRITER OMITTED IT
// - and the accompanying value is meaningless, so you must apply your own default
// instead (cl. 12.54.9). That distinction is the whole reason the flags exist: a
// fadeTo with no fade-time means "fade over Default_Fade_Time", NOT "fade in 0 ms".
// -----------------------------------------------------------------------------

// GET - report the last command this light was given.
bool GetPropertyLightingCommand(const uint32_t deviceInstance, const uint16_t objectType,
                                const uint32_t objectInstance, const uint32_t propertyIdentifier,
                                uint32_t* operation,
                                bool* useTargetLevel, float* targetLevel,
                                bool* useRampRate, float* rampRate,
                                bool* useStepIncrement, float* stepIncrement,
                                bool* useFadeTime, uint32_t* fadeTime,
                                bool* usePriority, uint32_t* priority) {
    if (deviceInstance != g_deviceInstance ||
        objectType != OBJECT_TYPE_LIGHTING_OUTPUT ||
        objectInstance != LIGHTING_OUTPUT_INSTANCE ||
        propertyIdentifier != PROPERTY_IDENTIFIER_LIGHTING_COMMAND) {
        return false;
    }

    // Hand back exactly what was last written - including which optional fields it
    // carried. The stack assembles the SEQUENCE from these.
    *operation = g_lightingCommand.operation;
    *useTargetLevel = g_lightingCommand.useTargetLevel;     *targetLevel = g_lightingCommand.targetLevel;
    *useRampRate = g_lightingCommand.useRampRate;           *rampRate = g_lightingCommand.rampRate;
    *useStepIncrement = g_lightingCommand.useStepIncrement; *stepIncrement = g_lightingCommand.stepIncrement;
    *useFadeTime = g_lightingCommand.useFadeTime;           *fadeTime = g_lightingCommand.fadeTime;
    *usePriority = g_lightingCommand.usePriority;           *priority = g_lightingCommand.priority;
    return true;
}

// SET - a client commands the light. This is what a lighting controller sends.
bool SetPropertyLightingCommand(const uint32_t deviceInstance, const uint16_t objectType,
                                const uint32_t objectInstance, const uint32_t propertyIdentifier,
                                const uint32_t operation,
                                const bool useTargetLevel, const float targetLevel,
                                const bool useRampRate, const float rampRate,
                                const bool useStepIncrement, const float stepIncrement,
                                const bool useFadeTime, const uint32_t fadeTime,
                                const bool usePriority, const uint32_t priority,
                                const uint8_t priorityForWriting, uint32_t* errorCode) {
    if (deviceInstance != g_deviceInstance ||
        objectType != OBJECT_TYPE_LIGHTING_OUTPUT ||
        objectInstance != LIGHTING_OUTPUT_INSTANCE ||
        propertyIdentifier != PROPERTY_IDENTIFIER_LIGHTING_COMMAND) {
        return false;
    }

    // Validate before accepting - a conformant device rejects a bad command rather
    // than obeying it. A Lighting Output's level is a percentage.
    if (useTargetLevel && (targetLevel < 0.0f || targetLevel > 100.0f)) {
        *errorCode = ERROR_CODE_VALUE_OUT_OF_RANGE;
        return false;
    }
    if (usePriority && (priority < 1 || priority > BACNET_PRIORITY_ARRAY_SIZE)) {
        *errorCode = ERROR_CODE_VALUE_OUT_OF_RANGE;
        return false;
    }

    // Remember the command so a read of Lighting_Command reports it back.
    g_lightingCommand.operation = operation;
    g_lightingCommand.useTargetLevel = useTargetLevel;     g_lightingCommand.targetLevel = targetLevel;
    g_lightingCommand.useRampRate = useRampRate;           g_lightingCommand.rampRate = rampRate;
    g_lightingCommand.useStepIncrement = useStepIncrement; g_lightingCommand.stepIncrement = stepIncrement;
    g_lightingCommand.useFadeTime = useFadeTime;           g_lightingCommand.fadeTime = fadeTime;
    g_lightingCommand.usePriority = usePriority;           g_lightingCommand.priority = priority;

    // Resolve the omitted optionals to this light's defaults - this is where the
    // use* flags earn their keep. A fadeTo that omitted fade-time fades over
    // Default_Fade_Time; it does NOT snap instantly because `fadeTime` happened to
    // arrive as 0.
    const uint32_t effectiveFadeTime = useFadeTime ? fadeTime : LIGHTING_DEFAULT_FADE_TIME;
    const float effectiveRampRate = useRampRate ? rampRate : LIGHTING_DEFAULT_RAMP_RATE;
    const float effectiveStepIncrement = useStepIncrement ? stepIncrement : LIGHTING_DEFAULT_STEP_INCREMENT;
    // A Lighting_Command that names no priority writes at Lighting_Command_Default_Priority.
    const uint8_t effectiveCommandPriority =
        (uint8_t)(usePriority ? priority : LIGHTING_COMMAND_DEFAULT_PRIORITY);

    // Apply the command to the light's level. ON REAL HARDWARE this is where you
    // would start the fade/ramp on your dimming driver and set In_Progress to
    // fadeActive/rampActive until it arrives. This example completes instantly and
    // reports In_Progress = idle, which is the honest answer for a device with no
    // dimming hardware behind it.
    const float currentLevel = ResolveLightingLevel(&g_lightingOutput);
    switch (operation) {
        case LIGHTING_OPERATION_FADE_TO:
            if (useTargetLevel) {
                CommandWrite(&g_lightingOutput, effectiveCommandPriority, (double)targetLevel);
                printf("Lighting_Command: fadeTo %.1f%% over %u ms @ priority %u\n",
                       targetLevel, effectiveFadeTime, effectiveCommandPriority);
            }
            break;
        case LIGHTING_OPERATION_RAMP_TO:
            if (useTargetLevel) {
                CommandWrite(&g_lightingOutput, effectiveCommandPriority, (double)targetLevel);
                printf("Lighting_Command: rampTo %.1f%% at %.1f%%/s @ priority %u\n",
                       targetLevel, effectiveRampRate, effectiveCommandPriority);
            }
            break;
        case LIGHTING_OPERATION_STEP_UP: {
            float next = currentLevel + effectiveStepIncrement;
            if (next > 100.0f) { next = 100.0f; }
            CommandWrite(&g_lightingOutput, effectiveCommandPriority, (double)next);
            printf("Lighting_Command: stepUp %.1f%% -> %.1f%% @ priority %u\n",
                   effectiveStepIncrement, next, effectiveCommandPriority);
            break;
        }
        case LIGHTING_OPERATION_STEP_DOWN: {
            float next = currentLevel - effectiveStepIncrement;
            if (next < 0.0f) { next = 0.0f; }
            CommandWrite(&g_lightingOutput, effectiveCommandPriority, (double)next);
            printf("Lighting_Command: stepDown %.1f%% -> %.1f%% @ priority %u\n",
                   effectiveStepIncrement, next, effectiveCommandPriority);
            break;
        }
        case LIGHTING_OPERATION_STOP:
            // Stop a fade/ramp in flight and hold the current level.
            g_lightingInProgress = LIGHTING_IN_PROGRESS_IDLE;
            printf("Lighting_Command: stop (holding at %.1f%%)\n", currentLevel);
            break;
        default:
            // Every other BACnetLightingOperation (warn / warnOff / warnRelinquish /
            // stepOn / stepOff / restoreOn / ...) is accepted and recorded, but this
            // example has no dimming hardware to act it out. We log it honestly
            // rather than pretend it did something.
            printf("Lighting_Command: %s accepted (recorded; no hardware to act on it)\n",
                   LightingOperationName(operation));
            break;
    }

    (void)priorityForWriting; // the command's own priority field is what drives the light
    return true;
}

// -----------------------------------------------------------------------------
// 2d. TimeSynchronization callback - the other B-LD addition (DM-TS-B)
//
// A lighting system broadcasts the time so every luminaire's scheduled scenes line
// up. The stack decodes the request and hands us the wall-clock fields; a real
// device would set its RTC here.
// -----------------------------------------------------------------------------
bool SetSystemTime(const uint32_t deviceInstance, const uint8_t year, const uint8_t month,
                   const uint8_t day, const uint8_t weekday, const uint8_t hour,
                   const uint8_t minute, const uint8_t second, const uint8_t hundrethSeconds) {
    (void)weekday;
    (void)hundrethSeconds;
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    // ON REAL HARDWARE: set your RTC here. `year` is an offset from 1900, per BACnet.
    printf("TimeSynchronization: %u-%02u-%02u %02u:%02u:%02u (device clock would be set here)\n",
           (unsigned)(1900 + year), month, day, hour, minute, second);
    return true;
}

// -----------------------------------------------------------------------------
// 2e. DeviceCommunicationControl callback - inherited from B-ASC (DM-DCC-B)
//
// A management station sends DeviceCommunicationControl to tell a device to stop
// or resume communicating - useful to quiet a noisy device during commissioning.
// The CAS BACnet Stack runs the actual enable/disable state machine (and the
// optional re-enable timer) for us; this callback's job is to (a) validate the
// optional password and (b) let the application know what was asked.
//
//   enableDisable: 0 = enable (resume), 1 = disable (stop initiating AND
//                  responding), 2 = disable-initiation (keep responding).
//   useTimeDuration/timeDuration: if set, the device auto-re-enables after
//                  timeDuration minutes. The stack handles that timer.
//
// Return true to accept (the stack then applies the new communication state), or
// false with *errorCode = password-failure to reject a bad password.
//
// NOTE (Protocol_Revision >= 20): the plain "disable" value (1) is DEPRECATED.
// Even if this callback accepts it, the stack rejects the request with
// service-request-denied - the standard now expects "disable-initiation" (2)
// (the device keeps answering reads but stops initiating). So at rev 24 only
// enable (0) and disable-initiation (2) actually take effect.
// -----------------------------------------------------------------------------
bool DeviceCommunicationControl(const uint32_t deviceInstance, const uint8_t enableDisable,
                                const char* password, const uint8_t passwordLength,
                                const bool useTimeDuration, const uint16_t timeDuration,
                                uint32_t* errorCode) {
    if (deviceInstance != g_deviceInstance) {
        return false;
    }

    // Check the password if this device requires one. A device with no configured
    // password (DCC_PASSWORD == "") accepts any request.
    //
    // The compare is length-checked first (so memcmp never reads past the wire
    // buffer, which is NOT null-terminated) and folds the byte comparison into a
    // single accumulator so it does not short-circuit on the first wrong byte -
    // a constant-time-style compare that avoids leaking how much of the password
    // matched via timing. On a mismatch we set *errorCode = password-failure; the
    // stack pairs that with Error Class = SECURITY (see clause 16.1.1.3.1).
    const size_t requiredLength = strlen(DCC_PASSWORD);
    if (requiredLength > 0) {
        unsigned diff = (password == NULL) ? 1u : (unsigned)(passwordLength ^ requiredLength);
        if (password != NULL && passwordLength == requiredLength) {
            for (size_t i = 0; i < requiredLength; ++i) {
                diff |= (unsigned)((unsigned char)password[i] ^ (unsigned char)DCC_PASSWORD[i]);
            }
        }
        if (diff != 0) {
            printf("DeviceCommunicationControl: REJECTED (password failure)\n");
            *errorCode = ERROR_CODE_PASSWORD_FAILURE;
            return false;
        }
    }

    // NOTE: the stack applies the deprecation rule AFTER this callback. For the
    // deprecated plain "disable" (1) at Protocol_Revision >= 20 it overrides our
    // acceptance and answers service-request-denied - so the line we print for
    // that case reflects the request received, not a state the device entered.
    const char* action = (enableDisable == DCC_ENABLE) ? "enable (resume communication)" :
                         (enableDisable == DCC_DISABLE) ? "disable (1) - DEPRECATED, the stack will reject this" :
                         (enableDisable == DCC_DISABLE_INITIATION) ? "disable-initiation (keep responding)" :
                         "unknown";
    if (useTimeDuration) {
        printf("DeviceCommunicationControl: %s for %u minute(s)\n", action, timeDuration);
    } else {
        printf("DeviceCommunicationControl: %s (indefinitely)\n", action);
    }
    // Return true to accept. We do NOT set *errorCode here: when a callback
    // returns false without setting it, the stack supplies a sensible default
    // error; we only write *errorCode to override that with a specific one (as the
    // password path above does, and as the SetProperty* callbacks do for
    // value-out-of-range).
    return true;
}

// -----------------------------------------------------------------------------
// 3. main()
// -----------------------------------------------------------------------------
int main(int argc, char** argv) {
    // Show printf output immediately, even when stdout is piped to a file.
    setvbuf(stdout, NULL, _IONBF, 0);

    // --- Command line + version --------------------------------------------
    // --help / --version print and exit, so handle them before we bind a socket
    // or touch the stack.
    if (CASExampleHelper::HandleHelpAndVersionArgs(argc, argv, APP_NAME, APP_VERSION)) {
        return 0;
    }
    const uint16_t port = CASExampleHelper::ParsePortArg(argc, argv, 47808);
    g_deviceInstance = CASExampleHelper::ParseDeviceIdArg(argc, argv, g_deviceInstance);
    CASExampleHelper::PrintVersion(APP_NAME, APP_VERSION);

    // --- Bind the BACnet/IP socket -----------------------------------------
    if (!CASExampleHelper::SetupUDP(port)) {
        return 1;
    }

    // Capture the BACnet/IP addressing the Network Port object will report.
    g_bacnetIpUdpPort = port;
    if (!CASExampleHelper::GetLocalIPv4(g_ipAddress, g_ipSubnetMask)) {
        printf("FYI: could not read a local IPv4 address; Network Port IP_Address "
               "will report 0.0.0.0.\n");
    }

    // --- Register callbacks -------------------------------------------------
    // The transport + time callbacks are shared boilerplate.
    CASExampleHelper::RegisterCommonCallbacks();
    // The property callbacks are specific to this example.
    BACnetStack_RegisterCallbackGetPropertyReal(GetPropertyReal);
    BACnetStack_RegisterCallbackGetPropertyEnumerated(GetPropertyEnumerated);
    BACnetStack_RegisterCallbackGetPropertyUnsignedInteger(GetPropertyUnsignedInteger);
    BACnetStack_RegisterCallbackGetPropertyCharacterString(GetPropertyCharString);
    BACnetStack_RegisterCallbackGetPropertyBool(GetPropertyBool);
    BACnetStack_RegisterCallbackGetPropertyOctetString(GetPropertyOctetString);
    // The "set" callbacks accept WriteProperty (DS-WP-B) to the commandable
    // outputs. One callback per written data type, plus the NULL callback that
    // relinquishes a priority slot.
    BACnetStack_RegisterCallbackSetPropertyReal(SetPropertyReal);
    BACnetStack_RegisterCallbackSetPropertyEnumerated(SetPropertyEnumerated);
    BACnetStack_RegisterCallbackSetPropertyUnsignedInteger(SetPropertyUnsignedInteger);
    BACnetStack_RegisterCallbackSetPropertyNull(SetPropertyNull);
    // The DeviceCommunicationControl callback makes this a B-ASC (DM-DCC-B).
    BACnetStack_RegisterCallbackDeviceCommunicationControl(DeviceCommunicationControl);
    // The Lighting_Command callbacks make this a B-LD (DS-LO-B). These are typed
    // callbacks: the stack assembles / decodes the BACnetLightingCommand SEQUENCE
    // and we deal only in plain numbers. See section 2c.
    BACnetStack_RegisterCallbackGetPropertyLightingCommand(GetPropertyLightingCommand);
    BACnetStack_RegisterCallbackSetPropertyLightingCommand(SetPropertyLightingCommand);
    // TimeSynchronization (DM-TS-B) - a lighting system tells us what time it is.
    BACnetStack_RegisterCallbackSetSystemTime(SetSystemTime);

    // --- Create the device --------------------------------------------------
    if (!BACnetStack_AddDevice(g_deviceInstance)) {
        printf("Error: Failed to add the Device %u.\n", g_deviceInstance);
        return 1;
    }

    // Enable the three services a B-ASC must execute: ReadProperty (DS-RP-B),
    // WriteProperty (DS-WP-B), and DeviceCommunicationControl (DM-DCC-B). We set
    // them explicitly to make the profile requirements obvious.
    //
    // We deliberately do NOT enable ReadPropertyMultiple, SubscribeCOV, or any
    // alarm/event service: an Application Specific Controller does not require
    // them, so a faithful B-ASC example leaves them off.
    if (!BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_READ_PROPERTY, true)) {
        printf("Error: Failed to enable the ReadProperty service.\n");
        return 1;
    }
    if (!BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_WRITE_PROPERTY, true)) {
        printf("Error: Failed to enable the WriteProperty service.\n");
        return 1;
    }
    if (!BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_DEVICE_COMMUNICATION_CONTROL, true)) {
        printf("Error: Failed to enable the DeviceCommunicationControl service.\n");
        return 1;
    }
    // TimeSynchronization (DM-TS-B) - the last service a B-LD must execute. The
    // profile allows DM-TS-B *or* DM-UTC-B; we do local time, so only this one.
    if (!BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_TIME_SYNCHRONIZATION, true)) {
        printf("Error: Failed to enable the TimeSynchronization service.\n");
        return 1;
    }

    // --- Add the read-only sensor objects -----------------------------------
    // Every stack setup call returns a bool; a real device should always check
    // it, so this example does too.
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_ANALOG_INPUT, ANALOG_INPUT_INSTANCE)) {
        printf("Error: Failed to add Analog Input 1 (Bronze).\n");
        return 1;
    }
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_BINARY_INPUT, BINARY_INPUT_INSTANCE)) {
        printf("Error: Failed to add Binary Input 1 (Emerald).\n");
        return 1;
    }
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_MULTI_STATE_INPUT, MULTI_STATE_INPUT_INSTANCE)) {
        printf("Error: Failed to add Multi-State Input 1 (Hot Pink).\n");
        return 1;
    }

    // --- Add the commandable OUTPUT objects (the B-SA additions) -------------
    // These accept WriteProperty. We make each one commandable below.
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_ANALOG_OUTPUT, ANALOG_OUTPUT_INSTANCE)) {
        printf("Error: Failed to add Analog Output 1 (Chartreuse).\n");
        return 1;
    }
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_BINARY_OUTPUT, BINARY_OUTPUT_INSTANCE)) {
        printf("Error: Failed to add Binary Output 1 (Fuchsia).\n");
        return 1;
    }
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_MULTI_STATE_OUTPUT, MULTI_STATE_OUTPUT_INSTANCE)) {
        printf("Error: Failed to add Multi-State Output 1 (Indigo).\n");
        return 1;
    }

    // --- Add the Lighting Output (the B-LD addition) ------------------------
    // This one object is why the profile exists. It is added with the plain
    // AddObject - the stack has no special Add*Object helper for it.
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_LIGHTING_OUTPUT, LIGHTING_OUTPUT_INSTANCE)) {
        printf("Error: Failed to add Lighting Output 1 (Jade).\n");
        return 1;
    }

    // --- Add the Network Port object ----------------------------------------
    // Every BACnet device (Protocol_Revision 17+) must have at least one Network
    // Port object describing the port it talks on. This one is the BACnet/IP
    // application port; it is the lowest layer, so its reference port is "none".
    if (!BACnetStack_AddNetworkPortObject(
            g_deviceInstance, NETWORK_PORT_INSTANCE,
            NETWORK_PORT_NETWORK_TYPE_IPV4,
            NETWORK_PORT_PROTOCOL_LEVEL_BACNET_APPLICATION,
            NETWORK_PORT_REFERENCE_PORT_NONE)) {
        printf("Error: Failed to add Network Port 1 (Vermilion).\n");
        return 1;
    }

    // --- Enable the OPTIONAL properties we choose to expose ------------------
    // The stack automatically enables an object's REQUIRED properties when the
    // object is added (AddObject / AddNetworkPortObject) - so Units, Polarity,
    // Number_Of_States, Out_Of_Service, and the Network Port's BACnet/IP
    // addressing (IP_Address, IP_Subnet_Mask, BACnet_IP_UDP_Port, ...) are
    // already enabled; our Get* callbacks just supply their values. Only
    // OPTIONAL properties need SetPropertyEnabled. State_Text is optional on a
    // Multi-State Input, so we enable it here (and serve it in GetPropertyCharString).
    if (!BACnetStack_SetPropertyEnabled(g_deviceInstance, OBJECT_TYPE_MULTI_STATE_INPUT,
                                        MULTI_STATE_INPUT_INSTANCE, PROPERTY_IDENTIFIER_STATE_TEXT, true)) {
        printf("Error: Failed to enable State_Text on Multi-State Input 1 (Hot Pink).\n");
        return 1;
    }

    // --- Make the output objects commandable --------------------------------
    // A commandable object's Present_Value is resolved from a 16-slot
    // Priority_Array plus a Relinquish_Default. For the stack to treat the object
    // that way - and to accept WriteProperty into it - three properties must be
    // turned on per object: Present_Value WRITABLE, and Priority_Array +
    // Relinquish_Default ENABLED. (Present_Value, Priority_Array, and
    // Relinquish_Default are all required properties, so the stack already
    // *enabled* them on AddObject; here we additionally mark Present_Value
    // writable, which is what flips the object into commandable mode.)
    // The Lighting Output joins the list: its Present_Value is commandable in
    // exactly the same way (a REAL level resolved from the Priority_Array), so it
    // needs exactly the same three calls. Nothing lighting-specific here.
    // Carry the INSTANCE alongside the type. This loop used to hardcode a literal
    // 1 for the instance while every other line in the file used the named
    // constants - so changing ANALOG_OUTPUT_INSTANCE would silently leave this
    // loop behind, and the object would start, answer Who-Is, and reject every
    // WriteProperty. Exactly the failure the comment above warns about.
    struct CommandableObject { uint16_t type; uint32_t instance; };
    const CommandableObject outputs[] = {
        { OBJECT_TYPE_ANALOG_OUTPUT,      ANALOG_OUTPUT_INSTANCE },
        { OBJECT_TYPE_BINARY_OUTPUT,      BINARY_OUTPUT_INSTANCE },
        { OBJECT_TYPE_MULTI_STATE_OUTPUT, MULTI_STATE_OUTPUT_INSTANCE },
        { OBJECT_TYPE_LIGHTING_OUTPUT,    LIGHTING_OUTPUT_INSTANCE },
    };
    for (size_t i = 0; i < sizeof(outputs) / sizeof(outputs[0]); ++i) {
        if (!BACnetStack_SetPropertyEnabled(g_deviceInstance, outputs[i].type, outputs[i].instance,
                                            PROPERTY_IDENTIFIER_PRIORITY_ARRAY, true) ||
            !BACnetStack_SetPropertyEnabled(g_deviceInstance, outputs[i].type, outputs[i].instance,
                                            PROPERTY_IDENTIFIER_RELINQUISH_DEFAULT, true) ||
            !BACnetStack_SetPropertyWritable(g_deviceInstance, outputs[i].type, outputs[i].instance,
                                             PROPERTY_IDENTIFIER_PRESENT_VALUE, true)) {
            printf("Error: Failed to make object type %u instance %u commandable.\n",
                   outputs[i].type, outputs[i].instance);
            return 1;
        }
    }

    // --- Make Lighting_Command writable (the B-LD addition) ------------------
    // Lighting_Command is REQUIRED *and WRITABLE* on a Lighting Output (cl. 12.54.9)
    // - writing it is what commands the light, so DS-LO-B is not satisfied without
    // this. The stack already enabled the property on AddObject (it is required);
    // marking it writable is what lets a client write it and routes the write to
    // our SetPropertyLightingCommand callback.
    if (!BACnetStack_SetPropertyWritable(g_deviceInstance, OBJECT_TYPE_LIGHTING_OUTPUT,
                                         LIGHTING_OUTPUT_INSTANCE,
                                         PROPERTY_IDENTIFIER_LIGHTING_COMMAND, true)) {
        printf("Error: Failed to make Lighting Output 1 (Jade) Lighting_Command writable.\n");
        return 1;
    }

    // Who-Is is answered automatically. The spec also requires a device to
    // announce itself on start-up, so broadcast an unsolicited I-Am now (to the
    // local subnet broadcast - the Network Port's own network).
    CASExampleHelper::SendIAm(g_deviceInstance);

    printf("FYI: Device %u (\"%s\") ready. Vendor ID %u. Press 'h' for help.\n",
           g_deviceInstance, DEVICE_NAME, VENDOR_IDENTIFIER);
    printf("FYI: Lighting Output 1 (Jade) starts at %.1f%% (off). WriteProperty its\n"
           "     Lighting_Command to fade/ramp/step it, or its Present_Value to set a level.\n",
           ResolveLightingLevel(&g_lightingOutput));

    // --- Run the stack ------------------------------------------------------
    // BACnetStack_Tick() processes incoming messages and timers. Call it
    // continuously, and poll the keyboard for interactive commands.
    bool running = true;
    while (running) {
        BACnetStack_Tick();

        switch (CASExampleHelper::PollKey()) {
            case CASExampleHelper::KeyCommand::Help:
                CASExampleHelper::PrintHelp(APP_NAME, APP_VERSION);
                break;
            case CASExampleHelper::KeyCommand::Quit:
                running = false;
                break;
            case CASExampleHelper::KeyCommand::ArrowUp:
                g_analogInput1Value += 1.1f;
                printf("Analog Input 1 (Bronze) = %.1f C\n", g_analogInput1Value);
                break;
            case CASExampleHelper::KeyCommand::ArrowDown:
                g_analogInput1Value -= 1.1f;
                printf("Analog Input 1 (Bronze) = %.1f C\n", g_analogInput1Value);
                break;
            case CASExampleHelper::KeyCommand::None:
            default:
                break;
        }

#if defined(_WIN32)
        Sleep(1); // 1 ms - be a good citizen, don't spin the CPU
#else
        usleep(1000);
#endif
    }

    CASExampleHelper::RestoreInput();
    CASExampleHelper::ShutdownUDP();
    return 0;
}
